/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package freqanalyzertest;

import java.awt.*;
import java.awt.Component;
import java.io.File;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.DefaultCellEditor;
import javax.swing.DefaultComboBoxModel;
import javax.swing.GroupLayout;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.LayoutStyle;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.*;
import javax.swing.table.TableCellEditor;
import javax.swing.table.TableCellRenderer;

public class MainFrame extends javax.swing.JFrame {

   public MainFrame() {
      initComponents();
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   // Generated using JFormDesigner Evaluation license - Leonid Karpov
   private void initComponents() {
       txtCrypted = new JLabel();
       txtDecrypted = new JLabel();
       btnLoadFile = new JToggleButton();
       txtFileName = new JLabel();
       jScrollPane1 = new JScrollPane();
       tableSubst = TableSubstCreate();
       txtDoubleCh = new JLabel();
       btnDecrypt = new JButton();
       jScrollPane2 = new JScrollPane();
       txtAreaDecrypt = new JTextArea();
       btnLeft = new JButton();
       btnRight = new JButton();
       txtFind = new JTextField();
       btnLoadFileFreqs = new JButton();
       txtFileNameFreqs = new JLabel();
       jButton1 = new JButton();

       //======== this ========
       setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
       setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
       setResizable(false);
       var contentPane = getContentPane();

       //---- txtCrypted ----
       txtCrypted.setFont(new Font("Courier New", Font.PLAIN, 12));
       txtCrypted.setText("\u0428\u0438\u0444\u0440\u043e\u0432\u0430\u043d\u043d\u044b\u0439 \u0442\u0435\u043a\u0441\u0442");

       //---- txtDecrypted ----
       txtDecrypted.setFont(new Font("Courier New", Font.PLAIN, 12));
       txtDecrypted.setText("\u0414\u0435\u0448\u0438\u0444\u0440\u043e\u0432\u0430\u043d\u043d\u044b\u0439 \u0442\u0435\u043a\u0441\u0442");

       //---- btnLoadFile ----
       btnLoadFile.setText("\u041e\u0442\u043a\u0440\u044b\u0442\u044c \u0448\u0438\u0444\u0440");
       btnLoadFile.addActionListener(e -> btnLoadFileActionPerformed(e));

       //======== jScrollPane1 ========
       {

           //---- tableSubst ----
           tableSubst.setModel(new DefaultTableModel(
               new Object[][] {
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
                   {null, null, null},
               },
               new String[] {
                   "\u0427\u0430\u0441\u0442\u043e\u0442\u043d\u043e\u0441\u0442\u044c", "\u0428\u0438\u0444\u0440", "\u0417\u0430\u043c\u0435\u043d\u0430"
               }
           ) {
               Class<?>[] columnTypes = new Class<?>[] {
                   String.class, String.class, Object.class
               };
               boolean[] columnEditable = new boolean[] {
                   false, false, true
               };
               @Override
               public Class<?> getColumnClass(int columnIndex) {
                   return columnTypes[columnIndex];
               }
               @Override
               public boolean isCellEditable(int rowIndex, int columnIndex) {
                   return columnEditable[columnIndex];
               }
           });
           jScrollPane1.setViewportView(tableSubst);
       }

       TableSubstInit();

       //---- txtDoubleCh ----
       txtDoubleCh.setText("\u0414\u0443\u0431\u043b\u0438\u0440\u0443\u044e\u0449\u0438\u0435\u0441\u044f \u0441\u0438\u043c\u0432\u043e\u043b\u044b");

       //---- btnDecrypt ----
       btnDecrypt.setText("\u0414\u0435\u0448\u0438\u0444\u0440\u043e\u0432\u0430\u0442\u044c");
       btnDecrypt.addActionListener(e -> btnDecryptActionPerformed(e));

       //======== jScrollPane2 ========
       {

           //---- txtAreaDecrypt ----
           txtAreaDecrypt.setEditable(false);
           txtAreaDecrypt.setColumns(20);
           txtAreaDecrypt.setFont(new Font("Tahoma", Font.PLAIN, 12));
           txtAreaDecrypt.setLineWrap(true);
           txtAreaDecrypt.setRows(5);
           txtAreaDecrypt.setFocusable(false);
           jScrollPane2.setViewportView(txtAreaDecrypt);
       }

       //---- btnLeft ----
       btnLeft.setText("<<");
       btnLeft.addActionListener(e -> btnLeftActionPerformed(e));

       //---- btnRight ----
       btnRight.setText(">>");
       btnRight.addActionListener(e -> btnRightActionPerformed(e));

       //---- btnLoadFileFreqs ----
       btnLoadFileFreqs.setText("\u041e\u0442\u043a\u0440\u044b\u0442\u044c \u0444\u0430\u0439\u043b \u0447\u0430\u0441\u0442\u043e\u0442");
       btnLoadFileFreqs.addActionListener(e -> btnLoadFileFreqsActionPerformed(e));

       GroupLayout contentPaneLayout = new GroupLayout(contentPane);
       contentPane.setLayout(contentPaneLayout);
       contentPaneLayout.setHorizontalGroup(
           contentPaneLayout.createParallelGroup()
               .addGroup(contentPaneLayout.createSequentialGroup()
                   .addContainerGap()
                   .addGroup(contentPaneLayout.createParallelGroup()
                       .addComponent(txtCrypted, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                       .addComponent(txtDecrypted, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                       .addGroup(contentPaneLayout.createSequentialGroup()
                           .addGroup(contentPaneLayout.createParallelGroup()
                               .addGroup(contentPaneLayout.createSequentialGroup()
                                   .addComponent(btnLeft)
                                   .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                   .addComponent(txtFind, GroupLayout.PREFERRED_SIZE, 43, GroupLayout.PREFERRED_SIZE)
                                   .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                   .addComponent(btnRight)
                                   .addGap(0, 190, Short.MAX_VALUE))
                               .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE))
                           .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                           .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                               .addComponent(jScrollPane2, GroupLayout.Alignment.TRAILING)
                               .addGroup(GroupLayout.Alignment.TRAILING, contentPaneLayout.createSequentialGroup()
                                   .addComponent(btnDecrypt, GroupLayout.PREFERRED_SIZE, 105, GroupLayout.PREFERRED_SIZE)
                                   .addGap(703, 703, 703))
                               .addComponent(txtDoubleCh, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                       .addGroup(contentPaneLayout.createSequentialGroup()
                           .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                               .addComponent(btnLoadFileFreqs, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                               .addComponent(btnLoadFile, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                           .addGap(18, 18, 18)
                           .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                               .addComponent(txtFileName, GroupLayout.DEFAULT_SIZE, 986, Short.MAX_VALUE)
                               .addComponent(txtFileNameFreqs, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                   .addContainerGap())
       );
       contentPaneLayout.setVerticalGroup(
           contentPaneLayout.createParallelGroup()
               .addGroup(contentPaneLayout.createSequentialGroup()
                   .addGap(16, 16, 16)
                   .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                       .addComponent(btnLoadFileFreqs, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                       .addComponent(txtFileNameFreqs, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                   .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                   .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                       .addComponent(btnLoadFile, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                       .addComponent(txtFileName, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                   .addGap(18, 18, 18)
                   .addComponent(txtCrypted)
                   .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                   .addComponent(txtDecrypted)
                   .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                   .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                       .addComponent(btnLeft)
                       .addComponent(btnRight)
                       .addComponent(txtFind, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                   .addGap(18, 18, Short.MAX_VALUE)
                   .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                       .addGroup(contentPaneLayout.createSequentialGroup()
                           .addComponent(txtDoubleCh)
                           .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                           .addComponent(btnDecrypt)
                           .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                           .addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE, 406, GroupLayout.PREFERRED_SIZE))
                       .addComponent(jScrollPane1))
                   .addContainerGap())
       );
       pack();
       setLocationRelativeTo(getOwner());

       //---- jButton1 ----
       jButton1.setText("jButton1");
   }// </editor-fold>//GEN-END:initComponents

   private javax.swing.JTable TableSubstCreate() {

      return new javax.swing.JTable()
      {
         public TableCellEditor getCellEditor(int row, int column) {
             int modelColumn = convertColumnIndexToModel( column );
             if (modelColumn == COL_COMBOBOX)
                 return col2Editors.get(row);
             else
                 return super.getCellEditor(row, column);
         }

         public TableCellRenderer getCellRenderer(int row, int column)
         {
            int modelColumn = convertColumnIndexToModel( column );
            if (modelColumn == COL_COMBOBOX)
               return col2ComboBoxes.get(row);
            else
               return super.getCellRenderer(row, column);
         }

      };
   }
   
   private void CreateFreqAnalyzer() {

      JFileChooser chooser = new JFileChooser(".");
      FileNameExtensionFilter filter = new FileNameExtensionFilter("Текстовые файлы (*.txt)", "txt");
      chooser.setFileFilter(filter);
      if (JFileChooser.APPROVE_OPTION == chooser.showDialog(this, "Открыть файл")) {
         File file = chooser.getSelectedFile();
         String pathName = file.getAbsolutePath();
         txtFileName.setText(pathName);
         try {
            freqAnalyzer = new FreqAnalyzer(pathName, "cp1251", txtFileNameFreqs.getText(), "utf-8", null);
            textBeginPos = 0;
            UpdateTextsPart();
         } catch (TxtFileException ex) {
            freqAnalyzer = null;
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
         } catch (FreqAnalyzerException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
         }
      }
   }

   private void btnLoadFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadFileActionPerformed
      if(txtFileNameFreqs.getText().isEmpty()) {
         JOptionPane.showMessageDialog(this, "Откройте файл частот");
         return;
      }

      CreateFreqAnalyzer();
      TableSubstFill();
      UpdateDoubleChText();
      TableSystAddModelListener();
   }//GEN-LAST:event_btnLoadFileActionPerformed

   private void btnDecryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDecryptActionPerformed
      if( (null == freqAnalyzer) || (0 != GetDoubleBgs().size()) )
         return;
      freqAnalyzer.Decrypt();
      textBeginPos = 0;
      UpdateTextsPart();
      this.txtAreaDecrypt.setText(freqAnalyzer.GetDecryptedText());
   }//GEN-LAST:event_btnDecryptActionPerformed

   private void btnLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeftActionPerformed
      String textToFind = txtFind.getText();
      if(!textToFind.isEmpty()) {
         String text = freqAnalyzer.GetDecryptedText();
         int startPos = textBeginPos;
         if(text.substring(startPos, startPos+textToFind.length()).equals(textToFind))
            startPos--;
         if(0 != startPos) {
            int pos = text.lastIndexOf(textToFind, startPos);
            if(-1 != pos)
               textBeginPos = pos;
         }
      }
      else
        textBeginPos -= TXT_PART_LEN;
      
      if(textBeginPos < 0)
         textBeginPos = 0;

      UpdateTextsPart();
   }//GEN-LAST:event_btnLeftActionPerformed

   private void btnRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRightActionPerformed
      String textToFind = txtFind.getText();
      if(!textToFind.isEmpty()) {
         String text = freqAnalyzer.GetDecryptedText();
         int startPos = textBeginPos;
         if(text.substring(startPos, startPos+textToFind.length()).equals(textToFind))
            startPos++;
         int pos = text.indexOf(textToFind, startPos);
         if(-1 != pos)
            textBeginPos = pos;
      }
      else
         textBeginPos += TXT_PART_LEN;

      UpdateTextsPart();
   }//GEN-LAST:event_btnRightActionPerformed

   private void btnLoadFileFreqsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadFileFreqsActionPerformed
      JFileChooser chooser = new JFileChooser(".");
      FileNameExtensionFilter filter = new FileNameExtensionFilter("Текстовые файлы (*.txt)", "txt");
      chooser.setFileFilter(filter);
      if (JFileChooser.APPROVE_OPTION == chooser.showDialog(this, "Открыть файл")) {
         File file = chooser.getSelectedFile();
         String pathName = file.getAbsolutePath();
         txtFileNameFreqs.setText(pathName);
      }
   }//GEN-LAST:event_btnLoadFileFreqsActionPerformed

   private void UpdateTextsPart() {
      txtCrypted.setText(freqAnalyzer.GetCryptedText(textBeginPos, TXT_PART_LEN));
      txtDecrypted.setText(freqAnalyzer.GetDecryptedText(textBeginPos, TXT_PART_LEN));
   }
   
   private void TableSubstInit() {
      tableSubst.setRowHeight(20);
      
      col2Editors = new ArrayList<TableCellEditor>();
      col2ComboBoxes = new ArrayList<JComboBoxCellRenderer>();
      for(int i = 0; i < 1089; i++)
      {
         JComboBoxCellRenderer jcb = new JComboBoxCellRenderer();
         jcb.setModel(new DefaultComboBoxModel<>());
         col2ComboBoxes.add(jcb);

         DefaultCellEditor ced = new DefaultCellEditor(jcb) {
            @Override
            public Component getTableCellEditorComponent(javax.swing.JTable table, Object value, boolean isSelected, int row, int column) {
               JComboBox jcb = (JComboBox) getComponent();
               jcb.setSelectedItem(jcb.getModel().getSelectedItem());               
               return jcb;
            }
         };
         col2Editors.add(ced);
      }
   }
   
   private void TableSubstFill() {
      if(null == freqAnalyzer)
         return;
          
      int row = 0;
      Iterator<FreqInfo> chs = freqAnalyzer.GetCryptedTextChars();
      while(chs.hasNext()) {
         FreqInfo elem = chs.next();
         tableSubst.setValueAt(String.format("%f", elem.freq), row, 0);
         tableSubst.setValueAt(elem.symb, row, 1);
         JComboBox jcb = col2ComboBoxes.get(row);
         jcb.setModel(new JComboBoxDataModel(freqAnalyzer, elem.symb));
         row++;
      }
   }
   
   private void TableSystAddModelListener() {
      tableSubst.getModel().addTableModelListener(new TableModelListener() {
        @Override
        public void tableChanged(TableModelEvent e) {
           if(COL_COMBOBOX == e.getColumn()) {
              UpdateDoubleChText();
           }
        }
      } );
   }
   
   private ArrayList<String> GetDoubleBgs() {
      ArrayList<String> doubleBgs = new ArrayList<>();
      ArrayList<Substitution> subst = freqAnalyzer.GetSubstitution();

      for(int i = 0; i < subst.size(); i++) {
         String current = subst.get(i).to;
         
         int j = i + 1;
         boolean found = false;
         while(!found && j < subst.size())
            found = current.equals(subst.get(j++).to);

         if(found && (-1 == doubleBgs.indexOf(current)))
            doubleBgs.add(current);
      }
      return doubleBgs;
   }
   
   private void UpdateDoubleChText() {
      ArrayList<String> doubleBgs = GetDoubleBgs();
      if(0 != doubleBgs.size()) {
        String doubles = "";
        for(int i = 0; i < doubleBgs.size(); i++)
           doubles += "{" + doubleBgs.get(i) + "}";
        txtDoubleCh.setText("Дублируется: " + doubles);
      }
      else
        txtDoubleCh.setText("");
   }

   public static void main(String args[]) {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
       */
      try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Windows".equals(info.getName())) {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      } catch (ClassNotFoundException ex) {
         java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (InstantiationException ex) {
         java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex) {
         java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {
         public void run() {
            new MainFrame().setVisible(true);
         }
      });
   }

   private FreqAnalyzer freqAnalyzer = null;
   private List<TableCellEditor> col2Editors = null;
   private List<JComboBoxCellRenderer> col2ComboBoxes = null;
   
   private static final int COL_COMBOBOX = 2;
   private static final int TXT_PART_LEN = 160;
   private int textBeginPos = 0;

   // Variables declaration - do not modify//GEN-BEGIN:variables
   // Generated using JFormDesigner Evaluation license - Leonid Karpov
   private JLabel txtCrypted;
   private JLabel txtDecrypted;
   private JToggleButton btnLoadFile;
   private JLabel txtFileName;
   private JScrollPane jScrollPane1;
   private JTable tableSubst;
   private JLabel txtDoubleCh;
   private JButton btnDecrypt;
   private JScrollPane jScrollPane2;
   private JTextArea txtAreaDecrypt;
   private JButton btnLeft;
   private JButton btnRight;
   private JTextField txtFind;
   private JButton btnLoadFileFreqs;
   private JLabel txtFileNameFreqs;
   private JButton jButton1;
   // End of variables declaration//GEN-END:variables
}
